// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.SEODataScraper
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("requestUrl")]
        public Uri RequestUrl { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("canonical")]
        public Uri Canonical { get; set; }

        [JsonProperty("lang")]
        public string Lang { get; set; }

        [JsonProperty("charset")]
        public string Charset { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("image")]
        public string Image { get; set; }

        [JsonProperty("favicons")]
        public Favicon[] Favicons { get; set; }

        [JsonProperty("author")]
        public string Author { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("keywords")]
        public string Keywords { get; set; }

        [JsonProperty("source")]
        public string Source { get; set; }

        [JsonProperty("price")]
        public string Price { get; set; }

        [JsonProperty("priceCurrency")]
        public string PriceCurrency { get; set; }

        [JsonProperty("availability")]
        public string Availability { get; set; }

        [JsonProperty("robots")]
        public string Robots { get; set; }

        [JsonProperty("jsonld")]
        public Jsonld[] Jsonld { get; set; }

        [JsonProperty("og:url")]
        public Uri OgUrl { get; set; }

        [JsonProperty("og:locale")]
        public string OgLocale { get; set; }

        [JsonProperty("og:locale:alternate")]
        public string OgLocaleAlternate { get; set; }

        [JsonProperty("og:title")]
        public string OgTitle { get; set; }

        [JsonProperty("og:type")]
        public string OgType { get; set; }

        [JsonProperty("og:description")]
        public string OgDescription { get; set; }

        [JsonProperty("og:determiner")]
        public string OgDeterminer { get; set; }

        [JsonProperty("og:site_name")]
        public string OgSiteName { get; set; }

        [JsonProperty("og:image")]
        public Uri OgImage { get; set; }

        [JsonProperty("og:image:secure_url")]
        public string OgImageSecureUrl { get; set; }

        [JsonProperty("og:image:type")]
        public string OgImageType { get; set; }

        [JsonProperty("og:image:width")]
        public string OgImageWidth { get; set; }

        [JsonProperty("og:image:height")]
        public string OgImageHeight { get; set; }

        [JsonProperty("twitter:title")]
        public string TwitterTitle { get; set; }

        [JsonProperty("twitter:description")]
        public string TwitterDescription { get; set; }

        [JsonProperty("twitter:image")]
        public Uri TwitterImage { get; set; }

        [JsonProperty("twitter:image:alt")]
        public string TwitterImageAlt { get; set; }

        [JsonProperty("twitter:card")]
        public string TwitterCard { get; set; }

        [JsonProperty("twitter:site")]
        public string TwitterSite { get; set; }

        [JsonProperty("twitter:site:id")]
        public string TwitterSiteId { get; set; }

        [JsonProperty("twitter:url")]
        public string TwitterUrl { get; set; }

        [JsonProperty("twitter:account_id")]
        public string TwitterAccountId { get; set; }

        [JsonProperty("twitter:creator")]
        public string TwitterCreator { get; set; }

        [JsonProperty("twitter:creator:id")]
        public string TwitterCreatorId { get; set; }

        [JsonProperty("twitter:player")]
        public string TwitterPlayer { get; set; }

        [JsonProperty("twitter:player:width")]
        public string TwitterPlayerWidth { get; set; }

        [JsonProperty("twitter:player:height")]
        public string TwitterPlayerHeight { get; set; }

        [JsonProperty("twitter:player:stream")]
        public string TwitterPlayerStream { get; set; }

        [JsonProperty("twitter:app:name:iphone")]
        public string TwitterAppNameIphone { get; set; }

        [JsonProperty("twitter:app:id:iphone")]
        public string TwitterAppIdIphone { get; set; }

        [JsonProperty("twitter:app:url:iphone")]
        public string TwitterAppUrlIphone { get; set; }

        [JsonProperty("twitter:app:name:ipad")]
        public string TwitterAppNameIpad { get; set; }

        [JsonProperty("twitter:app:id:ipad")]
        public string TwitterAppIdIpad { get; set; }

        [JsonProperty("twitter:app:url:ipad")]
        public string TwitterAppUrlIpad { get; set; }

        [JsonProperty("twitter:app:name:googleplay")]
        public string TwitterAppNameGoogleplay { get; set; }

        [JsonProperty("twitter:app:id:googleplay")]
        public string TwitterAppIdGoogleplay { get; set; }

        [JsonProperty("twitter:app:url:googleplay")]
        public string TwitterAppUrlGoogleplay { get; set; }

        [JsonProperty("headings")]
        public Heading[] Headings { get; set; }

        [JsonProperty("imgTags")]
        public ImgTag[] ImgTags { get; set; }

        [JsonProperty("responseBody")]
        public string ResponseBody { get; set; }

        [JsonProperty("viewport")]
        public string Viewport { get; set; }

        [JsonProperty("X-UA-Compatible")]
        public string XUaCompatible { get; set; }

        [JsonProperty("360-site-verification")]
        public string The360SiteVerification { get; set; }

        [JsonProperty("fb:app_id")]
        public string FbAppId { get; set; }

        [JsonProperty("msvalidate.01")]
        public string Msvalidate01 { get; set; }

        [JsonProperty("referrer")]
        public string Referrer { get; set; }

        [JsonProperty("y_key")]
        public string YKey { get; set; }

        [JsonProperty("google-site-verification")]
        public string GoogleSiteVerification { get; set; }

        [JsonProperty("google-adsense-account")]
        public string GoogleAdsenseAccount { get; set; }

        [JsonProperty("yandex-verification")]
        public string YandexVerification { get; set; }
    }

    public partial class Favicon
    {
        [JsonProperty("rel")]
        public string Rel { get; set; }

        [JsonProperty("href")]
        public Uri Href { get; set; }
    }

    public partial class Heading
    {
        [JsonProperty("level")]
        public Level Level { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }
    }

    public partial class ImgTag
    {
        [JsonProperty("src")]
        public Uri Src { get; set; }

        [JsonProperty("alt")]
        public string Alt { get; set; }
    }

    public partial class Jsonld
    {
        [JsonProperty("@context")]
        public Uri Context { get; set; }

        [JsonProperty("@type")]
        public string Type { get; set; }

        [JsonProperty("@id")]
        public Uri Id { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("author")]
        public Author Author { get; set; }

        [JsonProperty("isPartOf")]
        public IsPartOf IsPartOf { get; set; }

        [JsonProperty("inLanguage")]
        public string InLanguage { get; set; }

        [JsonProperty("sameAs")]
        public Uri[] SameAs { get; set; }
    }

    public partial class Author
    {
        [JsonProperty("@type")]
        public string Type { get; set; }

        [JsonProperty("@id")]
        public Uri Id { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("logo")]
        public Uri Logo { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("founder")]
        public Founder Founder { get; set; }

        [JsonProperty("foundingDate")]
        public DateTimeOffset FoundingDate { get; set; }

        [JsonProperty("foundingLocation")]
        public string FoundingLocation { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("legalName")]
        public string LegalName { get; set; }

        [JsonProperty("contactPoint")]
        public ContactPoint ContactPoint { get; set; }
    }

    public partial class ContactPoint
    {
        [JsonProperty("@type")]
        public string Type { get; set; }

        [JsonProperty("availableLanguage")]
        public AvailableLanguage[] AvailableLanguage { get; set; }

        [JsonProperty("contactOption")]
        public string ContactOption { get; set; }

        [JsonProperty("contactType")]
        public string ContactType { get; set; }

        [JsonProperty("telephone")]
        public string Telephone { get; set; }
    }

    public partial class AvailableLanguage
    {
        [JsonProperty("@type")]
        public string Type { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("alternateName")]
        public string AlternateName { get; set; }
    }

    public partial class Founder
    {
        [JsonProperty("@type")]
        public string Type { get; set; }

        [JsonProperty("@id")]
        public Uri Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public partial class IsPartOf
    {
        [JsonProperty("@type")]
        public string Type { get; set; }

        [JsonProperty("@id")]
        public Uri Id { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("potentialAction")]
        public PotentialAction PotentialAction { get; set; }
    }

    public partial class PotentialAction
    {
        [JsonProperty("@type")]
        public string Type { get; set; }

        [JsonProperty("target")]
        public string Target { get; set; }

        [JsonProperty("query-input")]
        public string QueryInput { get; set; }
    }

    public enum Level { H2, H3, H4 };
}
