// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.SEODataScraper
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("requestUrl")]
        public Uri RequestUrl { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("canonical")]
        public Uri Canonical { get; set; }

        [JsonProperty("lang")]
        public string Lang { get; set; }

        [JsonProperty("charset")]
        public string Charset { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("image")]
        public string Image { get; set; }

        [JsonProperty("favicons")]
        public Favicon[] Favicons { get; set; }

        [JsonProperty("author")]
        public string Author { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("keywords")]
        public string Keywords { get; set; }

        [JsonProperty("source")]
        public string Source { get; set; }

        [JsonProperty("price")]
        public string Price { get; set; }

        [JsonProperty("priceCurrency")]
        public string PriceCurrency { get; set; }

        [JsonProperty("availability")]
        public string Availability { get; set; }

        [JsonProperty("robots")]
        public string Robots { get; set; }

        [JsonProperty("jsonld")]
        public Jsonld[] Jsonld { get; set; }

        [JsonProperty("og:url")]
        public Uri OgUrl { get; set; }

        [JsonProperty("og:locale")]
        public string OgLocale { get; set; }

        [JsonProperty("og:locale:alternate")]
        public string OgLocaleAlternate { get; set; }

        [JsonProperty("og:title")]
        public string OgTitle { get; set; }

        [JsonProperty("og:type")]
        public string OgType { get; set; }

        [JsonProperty("og:description")]
        public string OgDescription { get; set; }

        [JsonProperty("og:determiner")]
        public string OgDeterminer { get; set; }

        [JsonProperty("og:site_name")]
        public string OgSiteName { get; set; }

        [JsonProperty("og:image")]
        public Uri OgImage { get; set; }

        [JsonProperty("og:image:secure_url")]
        public string OgImageSecureUrl { get; set; }

        [JsonProperty("og:image:type")]
        public string OgImageType { get; set; }

        [JsonProperty("og:image:width")]
        public long? OgImageWidth { get; set; }

        [JsonProperty("og:image:height")]
        public long? OgImageHeight { get; set; }

        [JsonProperty("twitter:title")]
        public string TwitterTitle { get; set; }

        [JsonProperty("twitter:description")]
        public string TwitterDescription { get; set; }

        [JsonProperty("twitter:image")]
        public Uri TwitterImage { get; set; }

        [JsonProperty("twitter:image:alt")]
        public string TwitterImageAlt { get; set; }

        [JsonProperty("twitter:card")]
        public string TwitterCard { get; set; }

        [JsonProperty("twitter:site")]
        public string TwitterSite { get; set; }

        [JsonProperty("twitter:site:id")]
        public string TwitterSiteId { get; set; }

        [JsonProperty("twitter:url")]
        public string TwitterUrl { get; set; }

        [JsonProperty("twitter:account_id")]
        public string TwitterAccountId { get; set; }

        [JsonProperty("twitter:creator")]
        public string TwitterCreator { get; set; }

        [JsonProperty("twitter:creator:id")]
        public string TwitterCreatorId { get; set; }

        [JsonProperty("twitter:player")]
        public string TwitterPlayer { get; set; }

        [JsonProperty("twitter:player:width")]
        public string TwitterPlayerWidth { get; set; }

        [JsonProperty("twitter:player:height")]
        public string TwitterPlayerHeight { get; set; }

        [JsonProperty("twitter:player:stream")]
        public string TwitterPlayerStream { get; set; }

        [JsonProperty("twitter:app:name:iphone")]
        public string TwitterAppNameIphone { get; set; }

        [JsonProperty("twitter:app:id:iphone")]
        public string TwitterAppIdIphone { get; set; }

        [JsonProperty("twitter:app:url:iphone")]
        public string TwitterAppUrlIphone { get; set; }

        [JsonProperty("twitter:app:name:ipad")]
        public string TwitterAppNameIpad { get; set; }

        [JsonProperty("twitter:app:id:ipad")]
        public string TwitterAppIdIpad { get; set; }

        [JsonProperty("twitter:app:url:ipad")]
        public string TwitterAppUrlIpad { get; set; }

        [JsonProperty("twitter:app:name:googleplay")]
        public string TwitterAppNameGoogleplay { get; set; }

        [JsonProperty("twitter:app:id:googleplay")]
        public string TwitterAppIdGoogleplay { get; set; }

        [JsonProperty("twitter:app:url:googleplay")]
        public string TwitterAppUrlGoogleplay { get; set; }

        [JsonProperty("headings")]
        public Heading[] Headings { get; set; }

        [JsonProperty("imgTags")]
        public Dictionary<string, string>[] ImgTags { get; set; }

        [JsonProperty("responseBody")]
        public string ResponseBody { get; set; }

        [JsonProperty("viewport")]
        public string Viewport { get; set; }

        [JsonProperty("googlebot")]
        public string Googlebot { get; set; }

        [JsonProperty("theme-color")]
        public string ThemeColor { get; set; }

        [JsonProperty("application-name")]
        public string ApplicationName { get; set; }

        [JsonProperty("msapplication-TileColor")]
        public string MsapplicationTileColor { get; set; }

        [JsonProperty("mobile-web-app-capable")]
        public string MobileWebAppCapable { get; set; }

        [JsonProperty("apple-mobile-web-app-title")]
        public string AppleMobileWebAppTitle { get; set; }

        [JsonProperty("apple-mobile-web-app-status-bar-style")]
        public string AppleMobileWebAppStatusBarStyle { get; set; }

        [JsonProperty("og:image:alt")]
        public string OgImageAlt { get; set; }
    }

    public partial class Favicon
    {
        [JsonProperty("rel")]
        public string Rel { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("href")]
        public string Href { get; set; }
    }

    public partial class Heading
    {
        [JsonProperty("level")]
        public Level? Level { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }
    }

    public partial class Jsonld
    {
        [JsonProperty("@context")]
        public Uri Context { get; set; }

        [JsonProperty("@type")]
        public string Type { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("logo")]
        public Uri Logo { get; set; }

        [JsonProperty("sameAs", NullValueHandling = NullValueHandling.Ignore)]
        public Uri[] SameAs { get; set; }

        [JsonProperty("potentialAction", NullValueHandling = NullValueHandling.Ignore)]
        public PotentialAction PotentialAction { get; set; }
    }

    public partial class PotentialAction
    {
        [JsonProperty("@type")]
        public string Type { get; set; }

        [JsonProperty("target")]
        public Target Target { get; set; }

        [JsonProperty("query-input")]
        public string QueryInput { get; set; }
    }

    public partial class Target
    {
        [JsonProperty("@type")]
        public string Type { get; set; }

        [JsonProperty("urlTemplate")]
        public string UrlTemplate { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }

    public enum Level { H1, H2, H3, H4, H5 };
}
